"""
Utilitaires de chiffrement pour données sensibles.
Utilise Fernet (AES 128-bit CBC) pour le chiffrement symétrique.
"""

import os
import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

from .logging import get_logger

logger = get_logger(__name__)


def get_encryption_key() -> bytes:
    """
    Récupère la clé de chiffrement depuis l'environnement.

    SECURITY CRITICAL: Fails fast if AUTH_ENCRYPTION_KEY is not set or invalid.
    This prevents falling back to a predictable/compromised key.

    Returns:
        Clé Fernet (32 bytes base64-encoded)

    Raises:
        RuntimeError: Si la clé n'est pas définie
        ValueError: Si la clé a un format invalide

    Note:
        La clé DOIT être définie dans AUTH_ENCRYPTION_KEY (environnement).
        Générer avec: python -m src.utils.encryption
    """
    # Lire depuis environnement
    key_b64 = os.getenv("AUTH_ENCRYPTION_KEY")

    if not key_b64:
        logger.critical(
            "❌ FATAL: AUTH_ENCRYPTION_KEY environment variable is NOT SET!\n"
            "   This is required to encrypt LinkedIn credentials securely.\n"
            "   \n"
            "   HOW TO FIX:\n"
            "   1. Generate a secure key: python -m src.utils.encryption\n"
            "   2. Copy the output: AUTH_ENCRYPTION_KEY=...\n"
            "   3. Add to your .env file or container environment\n"
            "   4. Restart the application\n"
        )
        raise RuntimeError(
            "AUTH_ENCRYPTION_KEY environment variable is REQUIRED and NOT SET. "
            "Please run: python -m src.utils.encryption to generate a secure key."
        )

    try:
        # Validate it's a proper Fernet key (44 chars base64)
        # This will raise InvalidToken if not a valid Fernet key
        Fernet(key_b64.encode('utf-8'))
        logger.info("✅ AUTH_ENCRYPTION_KEY validated successfully")
        return key_b64.encode('utf-8')
    except Exception as e:
        logger.error(f"❌ Invalid AUTH_ENCRYPTION_KEY format: {e}")
        logger.error("   Key must be a 44-character base64 string generated by Fernet.generate_key()")
        raise ValueError(
            f"AUTH_ENCRYPTION_KEY has invalid format. Error: {str(e)}\n"
            f"   Please run: python -m src.utils.encryption to generate a valid key."
        )


def encrypt_json(data: dict) -> str:
    """
    Chiffre un dictionnaire JSON et retourne une string base64.

    Args:
        data: Dictionnaire à chiffrer

    Returns:
        String base64 du contenu chiffré

    Raises:
        Exception: Si le chiffrement échoue
    """
    import json

    key = get_encryption_key()
    fernet = Fernet(key)

    # Sérialiser JSON (compact pour réduire taille)
    json_bytes = json.dumps(data, separators=(',', ':')).encode('utf-8')

    # Chiffrer
    encrypted_bytes = fernet.encrypt(json_bytes)

    # Encoder en base64 pour stockage
    return base64.b64encode(encrypted_bytes).decode('utf-8')


def decrypt_json(encrypted_b64: str) -> dict:
    """
    Déchiffre une string base64 et retourne un dictionnaire JSON.

    Args:
        encrypted_b64: String base64 du contenu chiffré

    Returns:
        Dictionnaire déchiffré

    Raises:
        InvalidToken: Si le déchiffrement échoue (clé invalide ou données corrompues)
        Exception: Si le parsing JSON échoue
    """
    import json

    key = get_encryption_key()
    fernet = Fernet(key)

    # Décoder base64
    encrypted_bytes = base64.b64decode(encrypted_b64)

    # Déchiffrer (lève InvalidToken si la clé est mauvaise)
    decrypted_bytes = fernet.decrypt(encrypted_bytes)

    # Parser JSON
    return json.loads(decrypted_bytes.decode('utf-8'))


def generate_new_key() -> str:
    """
    Génère une nouvelle clé Fernet aléatoire sécurisée.

    Returns:
        Clé Fernet encodée en base64 (44 caractères)

    Usage:
        >>> from src.utils.encryption import generate_new_key
        >>> new_key = generate_new_key()
        >>> print(f"Add this to your .env: AUTH_ENCRYPTION_KEY={new_key}")
    """
    return Fernet.generate_key().decode('utf-8')


if __name__ == "__main__":
    # Test du module
    logger.info("🔐 Encryption Module Test")
    logger.info("=" * 50)

    # Générer une nouvelle clé
    new_key = generate_new_key()
    logger.info(f"\n✅ New encryption key generated:")
    logger.info(f"AUTH_ENCRYPTION_KEY={new_key}")
    logger.warning(f"\n⚠️  Add this to your .env file!")

    # Test chiffrement/déchiffrement
    logger.info("\n" + "=" * 50)
    logger.info("Testing encryption/decryption...")

    test_data = {
        "cookies": [
            {"name": "li_at", "value": "test_session_token_12345"},
            {"name": "JSESSIONID", "value": "ajax:1234567890"}
        ],
        "origins": ["https://www.linkedin.com"]
    }

    try:
        # Chiffrer
        encrypted = encrypt_json(test_data)
        logger.info(f"✅ Encrypted (first 50 chars): {encrypted[:50]}...")

        # Déchiffrer
        decrypted = decrypt_json(encrypted)
        logger.info(f"✅ Decrypted successfully")
        logger.info(f"   Cookies count: {len(decrypted.get('cookies', []))}")

        # Vérifier intégrité
        assert decrypted == test_data, "Data mismatch!"
        logger.info(f"✅ Data integrity verified")

    except Exception as e:
        logger.error(f"❌ Error: {e}")

    logger.info("\n" + "=" * 50)
    logger.info("✅ All tests passed!")
